/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface Exchange extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): Exchange;
  clone(): Exchange;
  methods: {
    addLiquidity(_tokenAmount: number | string): PayableTransactionObject<void>;

    ethToTokenSwap(_minTokens: number | string): PayableTransactionObject<void>;

    tokenToEthSwap(
      _tokensSold: number | string,
      _minEth: number | string
    ): NonPayableTransactionObject<void>;

    getEthAmount(
      _tokenSold: number | string
    ): NonPayableTransactionObject<string>;

    getReserve(): NonPayableTransactionObject<string>;

    getTokenAmount(
      _ethSold: number | string
    ): NonPayableTransactionObject<string>;

    tokenAddress(): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
